//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLBCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaHD { get; set; }
        public string MaMH { get; set; }
        public int SoLuong { get; set; }
        public int Gia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
