//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLBCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public int SoLuongTon { get; set; }
        public int GiaMH { get; set; }
        public string MoTa { get; set; }
        public string AnhMH { get; set; }
        public string MaLMH { get; set; }
        public string MaNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LoaiMH LoaiMH { get; set; }
        public virtual NCC NCC { get; set; }
    }
}
